version: "3.8"
services: 
  react-front-end:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    environment: 
      - REACT_APP_HOST_IP_ADDRESS=http://localhost:3000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - "/app/node_modules"
      - "./:/app"
